title: ds-oliver
theme: minima

description: "A portfolio showcasing my data science and Python projects."
author:
  name: "Hogan"
  email: "hmarhoefer@gmail.com"
  github_username: "ds-oliver"

# This helps Jekyll generate RSS feeds, sitemaps, etc.
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# This tells Minima which pages to link in the site header
header_pages:
  - about.md
  - projects.md
  - contact.md