title: ds-oliver
theme: minima

description: "A portfolio showcasing my data science and Python projects."

author:
  name: "Hogan"
  email: "hmarhoefer@gmail.com"
  github_username: "ds-oliver"

# Jekyll plugins for RSS feed, SEO tags, and sitemap
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Pages to link in Minima’s top navigation
header_pages:
  - about.md
  - projects.md
  - contact.md
